apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kanarydeployments.kanary.k8s.io
spec:
  group: kanary.k8s.io
  names:
    kind: KanaryDeployment
    listKind: KanaryDeploymentList
    plural: kanarydeployments
    singular: kanarydeployment
    shortNames:
    - kd
    - kanary
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
